name: game_of_life_app
description: A Flutter implementation of Conway's Game of Life with interactive features
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Auskommentierte Assets - für ersten Test
  # assets:
  #   - assets/images/
  #   - assets/fonts/

  # fonts:
  #   - family: Orbitron
  #     fonts:
  #       - asset: assets/fonts/Orbitron-Regular.ttf
  #       - asset: assets/fonts/Orbitron-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Orbitron-Bold.ttf
  #         weight: 700