name: game_of_life_app
description: Eine interaktive Conway's Game of Life Simulation.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <= 3.8.0-278.2.beta"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  firebase_core: ^2.32.0
  # Die folgenden Abhängigkeiten werden für das Word Game benötigt, sind aber vorerst auskommentiert
  audioplayers: ^4.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # Für das Word Game
    - assets/sounds/
    - assets/music/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700


